<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="page-sitemap sitemap">
    <h1 class="page-title"><?php echo $this->getTitle() ?></h1>
    <div id="sitemap_top_links">
        <?php echo $this->getChildHtml('links') ?>
    </div>
    <?php echo $this->getChildHtml('pager_top') ?>
    <?php echo $this->getChildHtml('sitemap') ?>
    <?php echo $this->getChildHtml('links') ?>
    <?php echo $this->getChildHtml('pager_bottom') ?>
</div>
