<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>

<?php
    $_product = $this->getProduct();
    $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>

<div class="product-extra-actions pull-left span2">
    <?php if ($this->helper('wishlist')->isAllow()): ?>
        <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist wishlist-link"><?php echo $this->__('Add to Wishlist') ?></a>
    <?php endif ?>
    <?php if($_compareUrl): ?>
        <br>
        <a href="<?php echo $_compareUrl ?>" class="link-compare compaire-link"><?php echo $this->__('Add to Compare') ?></a>
    <?php endif ?>
    </ul>
</div>
