<?php
/**
 * Magento Customization
 * @Author : Abdullah
 *
 */
?>

<?php
	$height_feet_attr = Mage::getSingleton('eav/config')->getAttribute('customer','height_feet');
	$height_feet_attr_options = $height_feet_attr->getSource()->getAlloptions();
	
	$height_inch_attr = Mage::getSingleton('eav/config')->getAttribute('customer','height_inch');
	$height_inch_attr_options = $height_inch_attr->getSource()->getAlloptions();
	
	//Upper bound rules
$rules = array(
		array('height_feet'=>5,'height_inch'=>4,'body_weight'=>55,'chest'=>34,'jacket_length'=>27.5,'outseam'=>36.75,'trousers_inseem'=>27),
		array('height_feet'=>5,'height_inch'=>4,'body_weight'=>61,'chest'=>36,'jacket_length'=>27.5,'outseam'=>37,'trousers_inseem'=>27),
		array('height_feet'=>5,'height_inch'=>4,'body_weight'=>68,'chest'=>38,'jacket_length'=>28,'outseam'=>37,'trousers_inseem'=>26.75),
		array('height_feet'=>5,'height_inch'=>4,'body_weight'=>75,'chest'=>40,'jacket_length'=>28,'outseam'=>37.25,'trousers_inseem'=>26.75),								
		array('height_feet'=>5,'height_inch'=>4,'body_weight'=>82,'chest'=>42,'jacket_length'=>28.25,'outseam'=>37.5,'trousers_inseem'=>26.75),
		
		array('height_feet'=>5,'height_inch'=>6,'body_weight'=>68,'chest'=>38,'jacket_length'=>28.5,'outseam'=>37,'trousers_inseem'=>27),
		array('height_feet'=>5,'height_inch'=>6,'body_weight'=>75,'chest'=>40,'jacket_length'=>28.5,'outseam'=>38,'trousers_inseem'=>27.5),
		array('height_feet'=>5,'height_inch'=>6,'body_weight'=>82,'chest'=>42,'jacket_length'=>29,'outseam'=>38.5,'trousers_inseem'=>27.5),
		array('height_feet'=>5,'height_inch'=>6,'body_weight'=>91,'chest'=>44,'jacket_length'=>29,'outseam'=>39,'trousers_inseem'=>27.5),
		array('height_feet'=>5,'height_inch'=>6,'body_weight'=>98,'chest'=>46,'jacket_length'=>29.5,'outseam'=>39,'trousers_inseem'=>27),
		
		array('height_feet'=>5,'height_inch'=>8,'body_weight'=>70,'chest'=>38,'jacket_length'=>29.5,'outseam'=>40,'trousers_inseem'=>29),
		array('height_feet'=>5,'height_inch'=>8,'body_weight'=>77,'chest'=>40,'jacket_length'=>29.5,'outseam'=>40,'trousers_inseem'=>29),
		array('height_feet'=>5,'height_inch'=>8,'body_weight'=>84,'chest'=>42,'jacket_length'=>30,'outseam'=>40.5,'trousers_inseem'=>29),
		array('height_feet'=>5,'height_inch'=>8,'body_weight'=>93,'chest'=>44,'jacket_length'=>30,'outseam'=>40.5,'trousers_inseem'=>28.5),
		array('height_feet'=>5,'height_inch'=>8,'body_weight'=>100,'chest'=>46,'jacket_length'=>30.5,'outseam'=>40.5,'trousers_inseem'=>28.5),
		
		array('height_feet'=>5,'height_inch'=>10,'body_weight'=>73,'chest'=>38,'jacket_length'=>30.5,'outseam'=>41,'trousers_inseem'=>29.5),
		array('height_feet'=>5,'height_inch'=>10,'body_weight'=>80,'chest'=>40,'jacket_length'=>30.5,'outseam'=>41,'trousers_inseem'=>29.5),
		array('height_feet'=>5,'height_inch'=>10,'body_weight'=>86,'chest'=>42,'jacket_length'=>31,'outseam'=>41,'trousers_inseem'=>29),
		array('height_feet'=>5,'height_inch'=>10,'body_weight'=>95,'chest'=>44,'jacket_length'=>31,'outseam'=>41,'trousers_inseem'=>29),
		array('height_feet'=>5,'height_inch'=>10,'body_weight'=>102,'chest'=>46,'jacket_length'=>31.5,'outseam'=>41,'trousers_inseem'=>28.5),
		
		array('height_feet'=>6,'height_inch'=>0,'body_weight'=>74,'chest'=>38,'jacket_length'=>31.5,'outseam'=>42,'trousers_inseem'=>30.5),
		array('height_feet'=>6,'height_inch'=>0,'body_weight'=>82,'chest'=>40,'jacket_length'=>31.5,'outseam'=>42,'trousers_inseem'=>30.5),
		array('height_feet'=>6,'height_inch'=>0,'body_weight'=>89,'chest'=>42,'jacket_length'=>32,'outseam'=>42,'trousers_inseem'=>30),
		array('height_feet'=>6,'height_inch'=>0,'body_weight'=>96,'chest'=>44,'jacket_length'=>32,'outseam'=>42,'trousers_inseem'=>30),
		array('height_feet'=>6,'height_inch'=>0,'body_weight'=>105,'chest'=>46,'jacket_length'=>32.5,'outseam'=>42.5,'trousers_inseem'=>30),
		array('height_feet'=>6,'height_inch'=>0,'body_weight'=>111,'chest'=>48,'jacket_length'=>32.75,'outseam'=>42.5,'trousers_inseem'=>30),
		
		array('height_feet'=>6,'height_inch'=>2,'body_weight'=>75,'chest'=>38,'jacket_length'=>32.5,'outseam'=>43.5,'trousers_inseem'=>31.5),
		array('height_feet'=>6,'height_inch'=>2,'body_weight'=>83,'chest'=>40,'jacket_length'=>32.5,'outseam'=>43.5,'trousers_inseem'=>31.5),
		array('height_feet'=>6,'height_inch'=>2,'body_weight'=>90,'chest'=>42,'jacket_length'=>33,'outseam'=>43.5,'trousers_inseem'=>31.5),
		array('height_feet'=>6,'height_inch'=>2,'body_weight'=>98,'chest'=>44,'jacket_length'=>33,'outseam'=>44,'trousers_inseem'=>31),
		array('height_feet'=>6,'height_inch'=>2,'body_weight'=>107,'chest'=>46,'jacket_length'=>33.5,'outseam'=>44,'trousers_inseem'=>31),
		array('height_feet'=>6,'height_inch'=>2,'body_weight'=>112,'chest'=>48,'jacket_length'=>33.5,'outseam'=>44,'trousers_inseem'=>31),
		
		array('height_feet'=>6,'height_inch'=>4,'body_weight'=>77,'chest'=>38,'jacket_length'=>33.5,'outseam'=>44,'trousers_inseem'=>32.5),
		array('height_feet'=>6,'height_inch'=>4,'body_weight'=>84,'chest'=>40,'jacket_length'=>33.5,'outseam'=>45,'trousers_inseem'=>32.5),
		array('height_feet'=>6,'height_inch'=>4,'body_weight'=>93,'chest'=>42,'jacket_length'=>33.5,'outseam'=>45,'trousers_inseem'=>32),
		array('height_feet'=>6,'height_inch'=>4,'body_weight'=>100,'chest'=>44,'jacket_length'=>34,'outseam'=>45,'trousers_inseem'=>32),
		array('height_feet'=>6,'height_inch'=>4,'body_weight'=>107,'chest'=>46,'jacket_length'=>34,'outseam'=>45,'trousers_inseem'=>32),
		array('height_feet'=>6,'height_inch'=>4,'body_weight'=>114,'chest'=>48,'jacket_length'=>34,'outseam'=>45,'trousers_inseem'=>32.5)
		
		);
	
?>

<script type="text/javascript">
	jQuery.noConflict();
	var height_feet_json = <?php echo json_encode($height_feet_attr_options); ?>;
	var height_inch_json = <?php echo json_encode($height_inch_attr_options); ?>;
	var height_feet_val='';
	var height_inch_val='';
	var body_weight_val='';
	var upperbound_rules = <?php echo json_encode($rules); ?>;
	
	(jQuery)(function(){
				var slider = jQuery('ul.slider123').bxSlider({
					infiniteLoop: false,
					controls: false,
					pager: false,
					touchEnabled: false,
					useCss: false
				});
				
				if( slider ){
				
					var jwplay = new Array();
					var jwplay_instance = {};
					jQuery('ul.slider123 li.sliderli').each(function(index){
						this.lielmn = jQuery(this);
						this.jwplay_class = this.lielmn.find('.videoplayclass');
						jwplay_instance = {};
						if(this.jwplay_class.length>0)
						{
							this.videoelement_id = this.jwplay_class.attr('id');
							jwplay_instance = jwplayer(this.videoelement_id).setup({
								file: this.jwplay_class.attr('videopath'),
								height: 300,
								width: 400,
								image: '<?php echo $this->getSkinUrl('images/measurement/shirt-neck.png') ?>'
							});
							jwplay_instance.exists = 1;
						}
						else{
							jwplay_instance.exists = 0;
						}
						jwplay.push(jwplay_instance);
					});
					
					jQuery('#next_slide').on('click',function(){
						var active_slide = jQuery('ul.slider123 li.type').eq(slider.getCurrentSlide());
						var current_jwplay = jwplay[slider.getCurrentSlide()];
						if(current_jwplay.exists==1){
							
							if(current_jwplay.getState()=='PLAYING' || current_jwplay.getState()=='BUFFERING')
								current_jwplay.pause();
						}
					});
					
					jQuery('#prev_slide').on('click',function(){
						var active_slide = jQuery('ul.slider123 li.type').eq(slider.getCurrentSlide());
						var current_jwplay = jwplay[slider.getCurrentSlide()];
						if(current_jwplay.exists==1){
							
							if(current_jwplay.getState()=='PLAYING' || current_jwplay.getState()=='BUFFERING')
								current_jwplay.pause();
						}
					});
				
					var width_progress_bar = ((slider.getCurrentSlide()+1)/slider.getSlideCount())*100;
					jQuery('#progress_bar').css({width:width_progress_bar+'%'});
				
					jQuery('#prev_slide_clone').on('click',function(){
						slider.goToPrevSlide();
						jQuery('#prev_slide').show();
						jQuery('#next_slide').show();
					});
					
					jQuery('#prev_slide').on('click',function(){
						slider.goToPrevSlide();
						width_progress_bar = ((slider.getCurrentSlide()+1)/slider.getSlideCount())*100;
						jQuery('#progress_bar').css({width:width_progress_bar+'%'});
					});
					
					jQuery('#next_slide').on('click',function(){
						var currentslider = slider.getCurrentSlide();
						var currentslider_form = jQuery('ul.slider123 li.type').eq(currentslider).find('form');
						if( currentslider_form ){
							var form_data = currentslider_form.serialize();
							
							//if(currentslider_form.attr('name')=='form_initial_measurement'){
								var valdation_result = validate_form(currentslider_form,slider.getCurrentSlide());
							//}
							
							if( valdation_result ){
								//Sending ajax call to the save the attribute value into sales quote
								jQuery('#next_slide').attr('disabled','disabled');
								jQuery('#ajax_loader').show();
								jQuery.ajax({
									type	: "POST",
									cache	: false,
									dataType : 'json',
									url		: "<?php echo $this->getUrl('measurement/index/saveintocustomer') ?>",
									data	: form_data,
									success : function(result){
										jQuery('#ajax_loader').hide();
										if(result.status == 'SUCCESS'){
											slider.goToNextSlide();
											
											width_progress_bar = ((slider.getCurrentSlide()+1)/slider.getSlideCount())*100;
											jQuery('#progress_bar').css({width:width_progress_bar+'%'});
											
											slider_count = (slider.getSlideCount()-1);
											if( slider_count==slider.getCurrentSlide() ){
												jQuery('#prev_slide').hide();
												jQuery('#next_slide').hide();
											}
										}
										else{
											alert(result.message);
										}
										jQuery('#next_slide').removeAttr('disabled');
										jQuery.fancybox.resize();
									},
									failure : function(){
										jQuery('#next_slide').removeAttr('disabled');
									}
								});
							} //validation result
							
						}
						
					});
				}
				
		var checkout_url = '<?php echo $this->getUrl('checkout'); ?>';
		jQuery('.top-link-checkout').attr('href',checkout_url);		
			
		return;
	});

	function validate_form(form,current_slider)
	{
		var form = jQuery(form);
		var values = form.serializeArray();
		var count = 0;
		
		for (index = 0; index < values.length;++index) {
			if(values[index].name=='height_feet')
			{
				height_feet_val = getAttributeOptionLabel(height_feet_json,values[index].value);
			}
			
			if(values[index].name=='height_inch')
			{
				height_inch_val = getAttributeOptionLabel(height_inch_json,values[index].value);
			}
			
			if(values[index].name=='body_weight')
			{
				body_weight_val = values[index].value;
			}
			
			if(!values[index].value){
				count++;
			}
		}
		
		if(count>0){
			form.prev('.measurements_error').children('span').html('Please fill in the required fields.');
			//form.prev('.measurements_error').css({'visibility':'visible'});
			form.prev('.measurements_error').css({'display':'block'});
			return false;
		}
		else{
			if(current_slider>5){ //this value need to be changed if body shape get increased.
				upperbound_check = checkUpperBound(form);
				if(upperbound_check){
					if( form.prev('.measurements_error').hasClass('errorin') ){
						form.prev('.measurements_error').removeClass('errorin')
						//form.prev('.measurements_error').css({'visibility':'hidden'});
						form.prev('.measurements_error').css({'display':'none'});
						return true;
					}
					form.prev('.measurements_error').addClass('errorin');
					form.prev('.measurements_error').children('span').html('Value entered may not be correct. Please check it again, it might be approximately '+upperbound_check+' inches. But we might be wrong, in such case please click Next.');
					//form.prev('.measurements_error').css({'visibility':'visible'});
					form.prev('.measurements_error').css({'display':'block'});
					return false;
				}
			}
			//form.prev('.measurements_error').css({'visibility':'hidden'});
			form.prev('.measurements_error').css({'display':'none'});
			return true;
		}
	}
	
	function checkUpperBound(form)
	{
		/*alert(height_feet_val);
		alert(height_inch_val);
		alert(body_weight_val);*/
		var txt_elmn = form.find("input[type=text]");
		var txt_name = txt_elmn.attr('name');
		var upperbound_val = '';
		/*alert(txt_elmn.val());
		alert(txt_name);
		console.log(upperbound_rules);*/
		for (j = 0; j < upperbound_rules.length; ++j) {
			if( height_feet_val<=upperbound_rules[j].height_feet && height_inch_val<=upperbound_rules[j].height_inch && body_weight_val<=upperbound_rules[j].body_weight ){
				switch( txt_name )
				{
					case 'chest':
						upperbound_val = upperbound_rules[j].chest;	
						break;
					case 'jacket_length':
						upperbound_val = upperbound_rules[j].jacket_length;	
						break;
					case 'outseam':
						upperbound_val = upperbound_rules[j].outseam;	
						break;
					case 'trousers_inseem':
						upperbound_val = upperbound_rules[j].trousers_inseem;	
						break;
					default:
						upperbound_val = '';	
						break;
				}
				//alert(upperbound_val);
				//alert(txt_elmn.val());
				if(txt_elmn.val()==upperbound_val){
					return false;
				}else{
					return upperbound_val;
				}
				//alert(upperbound_val);
			}
		}
		
	}
	
	function getAttributeOptionLabel(json_configs,val)
	{
		for (i = 0; i < json_configs.length; ++i) {
			if(json_configs[i].value==val){
				return json_configs[i].label;
			}
		}
		return '';
	}
	
	
	
</script>


