<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h3 class="pull-left"><?php echo $this->__('Recent Orders') ?></h3>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>" class="pull-right btn-link"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <div class="clearfix"></div>
    <div class="table-box">
        <table class="data-table" id="my-orders-table">
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
            <thead>
                <tr>
                    <th><?php echo $this->__('Order #') ?></th>
                    <th><?php echo $this->__('Date') ?></th>
                    <th><?php echo $this->__('Ship To') ?></th>
                    <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                    <th><?php echo $this->__('Status') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td><?php echo $_order->getRealOrderId() ?></td>
                        <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                        <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                        <td class="a-center">
                            <span class="nobr">
                            <a href="<?php echo $this->getViewUrl($_order) ?>" class="btn-link"><?php echo $this->__('View Order') ?></a>
                            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                                <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder btn-link"><?php echo $this->__('Reorder') ?></a>
                            <?php endif ?>
                            </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
