<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $ibtheme = $this->helper('ibtheme');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ul class="product-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?> <?php echo $ibtheme->getProductClasses($_product) ?>">
            <div class="row">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image img span3"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(true)->resize(250, 250); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><div class="product-label">label</div></a>
                <?php // Product description ?>
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <div class="product-caption span6">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="title"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                    <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                    <hr>
                    <div class="pull-left">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <?php if(!$_product->isSaleable()): ?>
                            <span class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="pull-right">
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>
                    </div>
                    <div class="clearfix"></div>
                    <hr>
                    <div class="cart-button">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn btn-primary pull-left" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php endif; ?>
                            <div class="pull-left">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist wishlist-link"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <a href="<?php echo $_compareUrl ?>" class="link-compare compaire-link"><?php echo $this->__('Add to Compare') ?></a>
                                <?php endif; ?>
                            </div>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 100 ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>           
        <ul class="product-grid <?php if (Mage::getStoreConfig("ib_theme_design/general/store_productGrid") == 'type2') echo "two-vatiant" ?>">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php echo $ibtheme->getProductClasses($_product) ?>">
                <article>
                    <div class="border-top"></div>
                    <div class="border-left"></div>
                    <div class="border-right"></div>
                    <div class="border-bottom"></div>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(true)->resize(305, 305); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><div class="product-label">label</div></a>
                    <div class="product-caption">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <div class="inner">
                            <h3 class="title"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                            <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            <div class="cart-button">
                                <?php if($_product->isSaleable()): ?>
                                    <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart btn btn-primary"><?php echo $this->__('Add to Cart') ?></a>
                                <?php else: ?>
                                    <span class="link-cart availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span>
                                <?php endif ?>
                                <?php if ($this->helper('wishlist')->isAllow()): ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist wishlist-link"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <a href="<?php echo $_compareUrl ?>" class="link-compare compaire-link"><?php echo $this->__('Add to Compare') ?></a>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                </article>
                <?php if (Mage::getStoreConfig("ib_theme_design/general/store_productGrid") == 'type2') : ?>
                <div class="product-bottom-title">
                    <h3 class="title"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                </div>
                <?php endif; ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
