<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $ibtheme = $this->helper('ibtheme');

    if ($_product->isSaleable() && $this->hasOptions())
        $container1_html = trim($this->getChildChildHtml('container1', '', true, true));
    else
        $container1_html = '';
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="product-view <?php echo $ibtheme->getProductClasses($_product) ?>">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-shop">
                <h1 class="page-title"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

                <?php //if ($this->canEmailToFriend()): ?>
                <?php /*    <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p> */?>
                <?php //endif ?>
                <div class="row product-viev">
                    <div class="product-img-box span4 image">
                        <?php echo $this->getChildHtml('media') ?>
                    </div>
                    <div class="product-right-sidebar span8 product-caption">
                        <div class="row">
                            <div class="span8 top">
                                <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                            </div>
                            <?php if ($_product->getShortDescription()): ?>
                                <div class="short-description std span8"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?><hr></div>
                            <?php endif ?>
                        </div>

                    <?php echo $this->getChildHtml('other') ?>

                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                    <div class="row">
                            <div class="<?php echo empty($container1_html) ? 'span8 pull-left empty-container1' : 'span3 pull-left non-empty-container1' ?>"><?php echo $this->getChildHtml('product_type_data') ?></div>
                        <?php echo $container1_html ?>
                    </div>
                        
                    <?php if ( ! $this->hasOptions()): ?>
                        <hr>
                        <div class="row product-price-box">
                            <?php echo $this->getPriceHtml($_product) ?>
                            <div class="span5 pull-right">
                                <?php if ($_product->isSaleable()): ?>
                                    <div class="add-to-cart"><?php echo $this->getChildHtml('addtocart') ?></div>
                                <?php endif ?>

                                <?php echo $this->getChildHtml('addto') ?>
                                <?php echo $this->getChildHtml('extra_buttons') ?>
                            </div>
                        </div>

                    <?php elseif ( ! $_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    <?php endif ?>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <div class="span9">
                <?php if ($this->getChildChildHtml('container2', '', true, true)) : ?>
                    <div class="product-options-seven">
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    </div>
                <?php endif; ?>
                </div>
                <?php endif ?>
                <?php echo $this->getChildHtml('catalog.product.related') ?>
            </div>
                    
        </form>

        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>

    <div class="product-collateral">
        <div class="row">
            <div class="span12 product-tab">
                <?php echo $this->getChildHtml('info_tabs') ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('product_social') ?>
        <div class="pr-d-r-border"></div>
        <?php echo $this->getChildHtml('product_additional_data') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
    </div>
</div>
