<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="col2-set row">
    <div class="box span12">
        <div class="box-title row">
            <div class="span12">
                <h3><?php echo $this->__('Address Book') ?> <a href="<?php echo $this->getAddressBookUrl() ?>" class="btn-link"><?php echo $this->__('Manage Addresses') ?></a></h3>
            </div>
        </div>
        <div class="box-content row">
            <div class="col-1 span4">
                <h4><?php echo $this->__('Default Billing Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>" class="btn-link"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
            <div class="col-2 span5">
                <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>" class="btn-link"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
        </div>
    </div>
</div>
