<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="col2-set row">
    <div class="col-1 span4">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Contact Information') ?> <a href="<?php echo $this->getUrl('customer/account/edit') ?>" class="btn-link"><?php echo $this->__('Edit') ?></a></h4>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
                    <a href="<?php echo $this->getChangePasswordUrl() ?>" class="btn-link"><?php echo $this->__('Change Password') ?></a>
                </p>
            </div>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2 span5">
        <div class="box">
            <div class="box-title">
                <h4><?php echo $this->__('Newsletters') ?> <a href="<?php echo $this->getUrl('newsletter/manage') ?>" class="btn-link"><?php echo $this->__('Edit') ?></a></h4>
            </div>
            <div class="box-content">
                <p>
                    <?php if( $this->getIsSubscribed() ): ?>
                        <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                    <?php else: ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p>
            </div>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
    </div>
    <?php endif; ?>
</div>
