<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */

/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>
<?php $_cartQty = $this->getSummaryCount() ?>
<li id="cart" class="dropdown">
    <a href="#" data-toggle="dropdown"><?php echo $_cartQty > 0 ? $_cartQty : 0 ?><span class="arrow"></span></a>
        <div class="dropdown-menu">
            <?php $_items = $this->getRecentItems() ?>
            <?php if(count($_items)): ?>
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
                <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
            <?php else: ?>
                <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
            <?php endif ?>

            <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                <a href="<?php echo $this->getCheckoutUrl() ?>" class="view-shopping-cart btn btn-info"><?php echo $this->__('Checkout') ?></a>
            <?php endif ?>
        </div>
</li>
<?php endif;?>