<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <h4 class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></h4>
<?php else: ?>
    <table id="shopping-cart-totals-table">
        <col />
        <col width="1" />
        <tfoot>
            <?php echo $this->renderTotals('footer'); ?>
        </tfoot>
        <tbody>
            <?php echo $this->renderTotals(); ?>
        </tbody>
    </table>
<?php endif; ?>
