<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="form-add profuct-form-reviews">
    <h3><?php echo $this->__('Write Your Own Review') ?></h3>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
        <?php echo $this->getChildHtml('form_fields_before')?>
        <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
        <div id="product-review-table" class="rating-input data-table">
            <?php foreach ($this->getRatings() as $_rating): ?>
                <span class="quality"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?> <span class="required">*</span></span>
                <?php $number_price = 1; ?>
                <?php foreach ($_rating->getOptions() as $_option): ?>
                    <label>
                        <input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" /><br>
                        <?php echo $number_price; $number_price++; ?>
                    </label>
                <?php endforeach; ?>
                <span class="nbsp-large">nbsp-large</span>
                <div class="visible-440"></div>
            <?php endforeach; ?>
        </div>
        <?php endif ?>
        <div class="left">
            <label><?php echo $this->__('Nickname') ?> <span class="required">*</span></label>
            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
            <label><?php echo $this->__('Summary of Your Review') ?> <span class="required">*</span></label>
            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
        </div>
        <div class="right">
            <label><?php echo $this->__('Review') ?> <span class="required">*</span></label>
            <textarea name="detail" id="review_field" class="required-entry"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
            <div class="note"><?php echo $this->__('Note: HTML is not translated!') ?></div>
        </div>
        <div class="clearfix"></div>
        <span id="input-message-box"></span>

        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
        <script type="text/javascript">decorateTable('product-review-table')</script>
        <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button btn btn-primary"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
        
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                    var trs = $('product-review-table');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
    <?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
