<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="row">
    <div class="span9">
        <h1 class="page-title"><?php echo $this->__('Edit Account Information') ?></h1>
    </div>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" class="row account-info">
    <div class="fieldset span4">
        <?php echo $this->getBlockHtml('formkey')?>
        <h3 class="legend"><?php echo $this->__('Account Information') ?></h3>
        <div class="form-list">
            
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            
                <label for="email" class="required"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
            
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            
        </div>
    </div>
    <div class="fieldset span5" style="display:none;">
        <h3 class="legend"><?php echo $this->__('Change Password') ?></h3>
        <div class="form-list">
            <div>
                <label for="current_password" class="required"><?php echo $this->__('Current Password') ?> <span class="required">*</span></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </div>
            <div class="fields">
                <div class="field">
                    <label for="password" class="required"><?php echo $this->__('New Password') ?> <span class="required">*</span></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password') ?> <span class="required">*</span></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="buttons-set span9">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button btn btn-primary"><span><span><?php echo $this->__('Save') ?></span></span></button>
        <span class="required-field pull-right"><?php echo $this->__('* Required Fields') ?></span>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
