<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="row">
    <div class="span9">
        <h1 class="page-title title-buttons"><?php echo $this->__('Address Book') ?>
            <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button btn btn-primary pull-right" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
        </h1>
    </div>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col2-set addresses-list row">
    <div class="col-1 addresses-primary span4">
        <h3><?php echo $this->__('Default Addresses') ?></h3>
        <div>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            
                <h4><?php echo $this->__('Default Billing Address') ?></h4>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" class="btn-link"><?php echo $this->__('Change Billing Address') ?></a>
                <hr>
           
        <?php else: ?>
            
                <h4><?php echo $this->__('Default Billing Address') ?></h4>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            
                <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" class="btn-link"><?php echo $this->__('Change Shipping Address') ?></a>
            
        <?php else: ?>
            
                <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            
        <?php endif ?>
        </div>
    </div>
    <div class="col-2 addresses-additional span5">
        <h3><?php echo $this->__('Additional Address Entries') ?></h3>
        <div>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            
                <address>
                    <?php echo $this->getAddressHtml($_address) ?>
                </address>
                <a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>" class="btn-link"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove btn-link" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a>
            <hr>
            <?php endforeach; ?>
        <?php else: ?>
            
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            
        <?php endif ?>
        </div>
    </div>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
