<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?php echo $this->__('Update Wishlist') ?>" class="button btn-update btn btn-primary"><span><span><?php echo $this->__('Update Wishlist') ?></span></span></button>
<?php endif;?>
