<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */

/**
 * Grouped product data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 * @see Mage_Catalog_Block_Product_View_Type_Grouped
 */
?>
<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
    <span class="availability"><?php echo $this->__('Availability:') ?> <span class="in-stock"><?php echo $this->__('In stock') ?></span></span>
<?php else: ?>
    <span class="availability"><?php echo $this->__('Availability:') ?> <span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></span>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<hr>
<div class="product-options-four">
    <table class="data-table grouped-items-table" id="super-product-table">
        <col />
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th class="name"><?php echo $this->__('Product Name') ?></th>
                <?php if ($this->getCanShowProductPrice($_product)): ?>
                <th class="a-right price"><?php echo $this->__('Price') ?></th>
                <?php endif; ?>
                <?php if ($_product->isSaleable()): ?>
                <th class="a-center qty"><?php echo $this->__('Qty') ?></th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
            <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
            <tr>
                <td class="name"><?php echo $this->htmlEscape($_item->getName()) ?></td>
                <?php if ($this->getCanShowProductPrice($_product)): ?>
                <td class="a-right price">
                    <?php if ($this->getCanShowProductPrice($_item)): ?>
                    <?php echo $this->getPriceHtml($_item, true) ?>
                    <?php echo $this->getTierPriceHtml($_item) ?>
                    <?php endif; ?>
                </td>
                <?php endif; ?>
                <?php if ($_product->isSaleable()): ?>
                <td class="a-center qty">
                <?php if ($_item->isSaleable()) : ?>
                    <input type="text" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text" />
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        <?php else: ?>
           <tr>
               <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
           </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">decorateTable('super-product-table')</script>
