<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php if ($block_html = $this->getChildHtml('cms_column_products')): ?>
<div class="block column-products-block"><?php echo $block_html ?></div>
<?php endif ?>
