<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php if ($block_html = $this->getChildHtml('cms_home_header')): ?>
<?php echo $block_html ?>
<?php else : ?>
<div id="boxed" class="header-two-box">
    <ul id="header-two">
        <li></li>
    </ul>
</div>
<?php endif ?>
