<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks() ?>
<?php if (count($_links) > 0): ?>
<div class="span2">
<h4><?php echo $this->__("General Links") ?></h4>
<ul class="links"<?php if ($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif ?>>
    <?php foreach ($_links as $_link): ?>
        <?php if ($_link instanceof Mage_Core_Block_Abstract): ?>
            <?php echo $_link->toHtml() ?>
        <?php else: ?>
            <li<?php if ($_link->getIsFirst() || $_link->getIsLast()): ?> class="<?php if ($_link->getIsFirst()): ?>first<?php endif ?><?php if ($_link->getIsLast()): ?> last<?php endif ?>"<?php endif ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
</div>
<?php endif ?>