<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout btn btn-primary pull-right" onclick="review.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
