<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row">
    <div class="span9">
        <h1 class="page-title"><?php echo $this->__('My Product Reviews') ?></h1>
    </div>
</div>
<?php if( $this->getCollection() && $this->count()): ?>
    <div class="top">
        <?php echo $this->getToolbarHtml() ?>
    </div>
        <table class="data-table" id="my-reviews-table">
            <col width="1" />
            <col width="210" />
            <col width="1" />
            <col />
            <col width="1" />
            <tbody>
                <?php foreach ($this->getCollection() as $_review): ?>
                <tr>
                    <td><span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span></td>
                    <td class="name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></td>
                    <td>
                    <?php if($_review->getSum()): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    <?php endif; ?>
                    </td>
                    <td><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></td>
                    <td><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr btn-link"><?php echo $this->__('View Details') ?></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-reviews-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
