<?php
/**
 * Template Tag
 *
 * @category   TemplateTag
 * @package    TemplateTag_Stripe
 * @copyright  Copyright (c) 2013 Template Tag Ltd. (https://www.templatetag.com)
 * @license    https://www.templatetag.com/legal/end-user-licence-agreement/ (Template Tag EULA)
 * @author     Leon Smith <leon@templatetag.com>
 */
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/stripe/checkout.js') ?>"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
//<![CDATA[
    var TemplateTag = TemplateTag || {};
    TemplateTag.Stripe = <?php echo Mage::helper('stripe')->getStripeJson(); ?>;
    Stripe.setPublishableKey(TemplateTag.Stripe.PublishableKey);
//]]>
</script>