<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Ship to multiple address template
 *
 * @see Mage_Checkout_Block_Multishipping_Addresses
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="checkout_multishipping_form" action="<?php echo $this->getPostActionUrl() ?>" method="post" class="row cart-page multiple-addresses-page">
    <div class="multiple-checkout span12">
        <h1 class="page-title"><?php echo $this->__('Ship to Multiple Addresses') ?>
            <button type="button" title="<?php echo $this->__('Enter a New Address') ?>" class="button btn btn-primary pull-right" onclick="$('add_new_address_flag').value=1; $('checkout_multishipping_form').submit();"><span><span><?php echo $this->__('Enter a New Address') ?></span></span></button>
        </h1>


        <input type="hidden" name="continue" value="0" id="can_continue_flag" />
        <input type="hidden" name="new_address" value="0" id="add_new_address_flag" />
        <h3><?php echo $this->__('Please select shipping address for applicable items') ?></h3>
        <div class="table-box">
            <table class="data-table cart-table" id="multiship-addresses-table">
                <col />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <thead>
                    <tr>
                        <th><?php echo $this->__('Product') ?></th>
                        <th class="a-center"><?php echo $this->__('Qty') ?></th>
                        <th><?php echo $this->__('Send To') ?></th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="100" class="a-right"><button type="submit" title="<?php echo $this->__('Update Qty &amp; Addresses') ?>" class="button btn btn-primary" onclick="$('can_continue_flag').value=0"><span><span><?php echo $this->__('Update Qty &amp; Addresses') ?></span></span></button></td>
                    </tr>
                </tfoot>
                <tbody>
                <?php foreach ($this->getItems() as $_index => $_item): ?>
                    <?php if ($_item->getQuoteItem()) :?>
                    <tr>
                        <td class="name"><?php echo $this->getItemHtml($_item->getQuoteItem())?></td>
                        <td><input type="text" name="ship[<?php echo $_index ?>][<?php echo $_item->getQuoteItemId() ?>][qty]" value="<?php echo $this->htmlEscape($_item->getQty()) ?>" size="2" class="input-text qty" /></td>
                        <td><?php if ($_item->getProduct()->getIsVirtual()): echo $this->__('Shipping selection is not applicable.'); else: echo $this->getAddressesHtmlSelect($_item, $_index); endif; ?></td>
                        <td class="a-center"><a href="<?php echo $this->getItemDeleteUrl($_item) ?>" title="<?php echo $this->__('Remove Item') ?>" class="btn-remove2 close"><?php echo $this->__('Remove Item') ?></a></td>
                    </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <script type="text/javascript">decorateTable('multiship-addresses-table')</script>
        <div class="buttons-set">
            <a href="<?php echo $this->getBackUrl() ?>" class="btn btn-link"><small>&lt; </small><?php echo $this->__('Back to Shopping Cart') ?></a>
            <button type="submit" title="<?php echo $this->__('Continue to Shipping Information') ?>" class="btn btn-primary pull-right button<?php if ($this->isContinueDisabled()):?> disabled<?php endif; ?>" onclick="$('can_continue_flag').value=1"<?php if ($this->isContinueDisabled()):?> disabled="disabled"<?php endif; ?>><span><span><?php echo $this->__('Continue to Shipping Information') ?></span></span></button>
        </div>
    </div>
</form>
