<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Multishipping checkout billing information
 *
 * @see Mage_Checkout_Block_Multishipping_Billing
 */
?>
<div class="multiple-checkout row">
    <div class="span12">
        <h1 class="page-title"><?php echo $this->__('Billing Information') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <script src="<?php echo Mage::getBaseUrl('js') ?>varien/payment.js" type="text/javascript"></script>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="multishipping-billing-form">
        <div class="col2-set">
            <div class="col-1 col-narrow span6">
                <div class="box">
                    <div class="shipping-sub-title">
                        <b><?php echo $this->__('Billing Address') ?> <span class="separator">|</span></b> <a href="<?php echo $this->getSelectAddressUrl() ?>" class="edit"><?php echo $this->__('Change') ?></a>
                    </div>
                    <div class="box-content">
                        <?php $_address=$this->getAddress() ?>
                        <address><?php echo $_address->format('html') ?></address>
                    </div>
                </div>
            </div>
            <div class="col-2 col-wide span6">
                <div class="box">
                    <div class="shipping-sub-title">
                        <b><?php echo $this->__('Payment Method') ?></b>
                    </div>
                    <div class="box-content">
                        <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                            <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
                            <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                        </div>
                        <!-- Payment methods forms list -->
                        <div class="sp-methods">
                        <?php
                            $_methods       = $this->getMethods();
                            $_methodsCount  = count($_methods);
                        ?>
                        <?php foreach ($_methods as $_method): $_code = $_method->getCode() ?>
                            <div>
                                <?php if ($_methodsCount > 1): ?>
                                <label class="radio">
                                <input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
                                <?php else :?>
                                <span class="no-display"><input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" checked="checked" class="radio" /></span>
                                <?php endif;?>
                                <?php echo $_method->getTitle() ?></label>
                            </div>
                            <?php if($html = $this->getChildHtml('payment.method.'.$_code)) : ?>
                            <div>
                                <?php echo $html; ?>
                            </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </div>
                        <?php echo $this->getChildHtml('checkout_billing_items') ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="buttons-set span12">
            <a href="<?php echo $this->getBackUrl() ?>" class="btn btn-link pull-left"><small>&lt; </small><?php echo $this->__('Back to Shipping Information') ?></a>
            <button type="submit" title="<?php echo $this->__('Continue to Review Your Order') ?>" class="button btn btn-primary pull-right"><span><span><?php echo $this->__('Continue to Review Your Order') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var payment = new paymentForm('multishipping-billing-form');
        function toggleToolTip(event){
            if($('payment-tool-tip')){
                /*$('payment-tool-tip').setStyle({
                    top: (Event.pointerY(event)-510)+'px',
                    left: (Event.pointerX(event)-800)+'px'
                })*/
                $('payment-tool-tip').toggle();
            }
            Event.stop(event);
        }
        if($('payment-tool-tip-close')){
            Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
        }
        $$('.cvv-what-is-this').each(function(element){
            Event.observe(element, 'click', toggleToolTip);
        });
    //]]>
    </script>
</div>
