<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>

<?php  $_order = $this->getOrder() ?>
<a href="<?php echo $this->getPrintUrl($_order) ?>" class="link-print btn btn-primary pull-right" onclick="this.target='_blank';"><?php echo $this->__('Print') ?></a>
<?php echo $this->getChildHtml(); ?>
