<?php
/**
 * Template Tag
 *
 * @category   TemplateTag
 * @package    TemplateTag_Stripe
 * @copyright  Copyright (c) 2013 Template Tag Ltd. (https://www.templatetag.com)
 * @license    https://www.templatetag.com/legal/end-user-licence-agreement/ (Template Tag EULA)
 * @author     Leon Smith <leon@templatetag.com>
 */
?>
<div class="powered-by-stripe">
    <a href="https://stripe.com/" title="<?php echo $this->__('Powered by Stripe'); ?>" target="_blank">
        <img src="<?php echo $this->getImageSrc(); ?>" alt="<?php echo $this->__('Powered by Stripe'); ?>" />
    </a>
</div>
