<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $ibtheme = $this->helper('ibtheme') ?>
<div class="widget widget-new-products">
    <div class="widget-products <?php if (Mage::getStoreConfig("ib_theme_design/general/store_productGrid") == 'type2') echo "two-vatiant" ?>">
    <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="product-grid">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php echo $ibtheme->getProductClasses($_product) ?>">
                <article>
                    <div class="border-top"></div>
                    <div class="border-left"></div>
                    <div class="border-right"></div>
                    <div class="border-bottom"></div>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(true)->resize(305, 305); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><div class="product-label">label</div></a>
                    <div class="product-caption">
                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                        <div class="inner">
                            <h3 class="title"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <div class="cart-button">
                                <?php if($_product->isSaleable()): ?>
                                    <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart btn btn-primary"><?php echo $this->__('Add to Cart') ?></a>
                                <?php else: ?>
                                    <span class="link-cart availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span>
                                <?php endif ?>
                                <?php if ($this->helper('wishlist')->isAllow()): ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist wishlist-link"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <a href="<?php echo $_compareUrl ?>" class="link-compare compaire-link"><?php echo $this->__('Add to Compare') ?></a>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                </article>
                <?php if (Mage::getStoreConfig("ib_theme_design/general/store_productGrid") == 'type2') : ?>
                <div class="product-bottom-title">
                    <h3 class="title"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                </div>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
</div>
<?php endif ?>
