<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="block block-progress opc-block-progress progress-box">
    <h6><?php echo $this->__('Your Checkout Progress') ?></h6>
    
    <div class="block-content">
        <ol>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if ($this->isStepComplete('billing')): ?>
            <li class="complete">
                <?php echo $this->__('Billing Address') ?> <span class="separator">|</span>
                <a href="#billing" onclick="checkout.gotoSection('billing'); return false;" class="edit pull-right"><?php echo $this->__('Edit') ?></a>
            </li>
            <li class="complete">
                <aliress><?php echo $this->getBilling()->format('html') ?></aliress>
            </li>
        <?php else: ?>
            <li>
                <?php echo $this->__('Billing Address') ?>
            </li>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping')): ?>
            <li class="complete">
                <?php echo $this->__('Shipping Address') ?> <span class="separator">|</span>
                <a href="#payment" onclick="checkout.gotoSection('shipping');return false;" class="edit pull-right"><?php echo $this->__('Edit') ?></a>
            </li>
            <li class="complete">
                <aliress><?php echo $this->getShipping()->format('html') ?></aliress>
            </li>
        <?php else: ?>
            <li>
                <?php echo $this->__('Shipping Address') ?>
            </li>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping_method')): ?>
            <li class="complete">
                <?php echo $this->__('Shipping Method') ?> <span class="separator">|</span>
                <a href="#shipping_method" onclick="checkout.gotoSection('shipping_method'); return false;" class="edit pull-right"><?php echo $this->__('Edit') ?></a>
            </li>
            <li class="complete">
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo $this->escapeHtml($this->getShippingDescription()) ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif; ?>
            </li>
        <?php else: ?>
            <li>
                <?php echo $this->__('Shipping Method') ?>
            </li>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if ($this->isStepComplete('payment')): ?>
            <li class="complete">
                <?php echo $this->__('Payment Method') ?> <span class="separator">|</span>
                <a href="#payment" onclick="checkout.gotoSection('payment'); return false;" class="edit pull-right"><?php echo $this->__('Edit') ?></a>
            </li>
            <li class="complete">
                <?php echo $this->getPaymentHtml() ?>
            </li>
        <?php else: ?>
            <li>
                <?php echo $this->__('Payment Method') ?>
            </li>
        <?php endif; ?>
        <?php endif; ?>
        </ol>
    </div>
</div>
</div>
