<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>

<?php $_items = $this->getReviewsCollection()->getItems() ?>

<div class="box-collateral box-reviews product-reviews" id="customer-reviews">
    <?php if (count($_items)): ?>
        <h3><?php echo $this->__('Customer Reviews') ?></h3>
        <?php echo $this->getChildHtml('toolbar') ?>
        <ul>
            <?php foreach ($_items as $_review):?>
            <li>
                <div class="title"><?php echo $this->htmlEscape($_review->getTitle()) ?></div>
                <div class="title"><span><?php echo $this->htmlEscape($_review->getNickname()) ?></span>, <time datetime="<?php echo $this->formatDate($_review->getCreatedAt()) ?>"><?php echo $this->formatDate($_review->getCreatedAt()) ?></time></div>
                <?php $_votes = $_review->getRatingVotes(); ?>
                <?php if (count($_votes)): ?>
                <div class="review-rating">
                    <?php foreach ($_votes as $_vote): ?>
                        <span><?php echo $this->escapeHtml($_vote->getRatingCode()) ?>&nbsp;&nbsp;
                            <span class="rating-box">
                                <span class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></span>
                            </span>
                        </span>
                        <span class="separator">|</span>
                    <?php endforeach; ?>
                </div>
                <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
                <?php endif ?>
            </li>
            <?php endforeach ?>
        </ul>
        <?php echo $this->getChildHtml('toolbar') ?>
    <?php endif ?>

    <?php echo $this->getChildHtml('review_form') ?>
</div>
