<?php
    $config = Mage::getStoreConfig('dresscodeconfig/dresscodeconfig_mainfront');
?>
<div class="block block-tags">
    <div class="block-title">
        <strong><span><?php echo $this->__('Tags'); ?></span></strong>
    </div>
    <div class="block-content">

        <div class="tagcloud_flash">
            <?php
                if($config['tagcloud']=='flash')
                {
                 ?>

                    <script type="text/javascript">
                    AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0','width','220','height','150','title','flash','src','<?php echo str_replace('/skin/frontend/base/default/', '/', $this->getSkinUrl(tagcloud)); ?>','quality','high', 'wmode', 'transparent', 'pluginspage','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash','movie','<?php echo str_replace('/skin/frontend/base/default/', '/', $this->getSkinUrl(tagflash)); ?>','FlashVars', 'url=<?php echo str_replace('/skin/frontend/base/default/', '/', $this->getSkinUrl('tagflash.php')); ?>');

                    //end AC code
                    </script>

                 <?php
                }
                else
                {
                 ?>
                    <ul class="tags-list">
                        <?php foreach ($this->getTags() as $_tag): ?>
                            <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                 <?php
                }
            ?>

        </div>
        <ul class="tags-list tags-list-devices">
            <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>






    </div>
</div>


