<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="multiple-checkout">
    <div>
        <h1 class="page-title title-buttons"><?php echo $this->__('Change Billing Address') ?><button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button btn btn-primary pull-right" onclick="setLocation('<?php echo $this->getAddNewUrl() ?>')"><span><span><?php echo $this->__('Add New Address') ?></span></span></button></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $_index=0 ?>
    <?php foreach ($this->getAddressCollection() as $_address): ?>
        <?php if($_index%3==0): ?><div class="col3-set"><?php endif; ?>
        <div class="col-<?php echo ($_index%3+1) ?>">
                <p class="actions">
                    <a href="<?php echo $this->getEditAddressUrl($_address) ?>" class="edit"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> 
                    <a href="<?php echo $this->getSetAddressUrl($_address) ?>" class="btn-link"><?php echo $this->__('Select Address') ?></a>
                </p>
                <address>
                    <?php echo $_address->format('html') ?>
                </address>
                <?php if($this->isAddressDefaultBilling($_address)): ?>
                   <strong><?php echo $this->__('Default Billing') ?></strong>
                <?php endif; ?>
                <?php if($this->isAddressDefaultShipping($_address)): ?>
                    <br /><strong><?php echo $this->__('Default Shipping') ?></strong>
                <?php endif; ?>
        </div>
        <?php $_index++ ?>
        <?php if($_index && $_index%3==0): ?></div><?php endif; ?>
    <?php endforeach; ?>
    <?php if(!$_index || $_index%3!=0): ?></div><?php endif; ?>
    <div class="buttons-set">
        <a href="<?php echo $this->getBackUrl() ?>" class="btn btn-link"><small>&lt; </small><?php echo $this->__('Back to Billing Information') ?></a>
    </div>
</div>
