<?php
/**
 * Magento Customization
 * @Author : Abdullah
 *
 */
?>

<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn btn-info btn-large pull-right btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> <?php /* onclick="window.location='<?php //echo $this->getCheckoutUrl() ?>';" */ ?> ><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
<?php endif?>