<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="row">
    <div class="span9">
        <h1 class="page-title"><?php echo $this->__('Share Your Wishlist') ?></h1>
    </div>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h3 class="legend"><?php echo $this->__('Sharing Information') ?></h3>
        <div class="form-list">
            
                <label for="email_address" class="required"><?php echo $this->__('Email addresses, separated by commas') ?> <span class="required">*</span></label>
                <div class="input-box">
                    <textarea name="emails" cols="60" rows="5" id="email_address" class="validate-emails required-entry"><?php echo $this->getEnteredData('emails') ?></textarea>
                </div>
            
            
                <label for="message"><?php echo $this->__('Message') ?></label>
                <div class="input-box">
                    <textarea id="message" name="message" cols="60" rows="5"><?php echo $this->getEnteredData('message') ?></textarea>
                </div>
            
            <?php if($this->helper('wishlist')->isRssAllow()): ?>
            
                <div class="input-box">
                    <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?>" class="checkbox" />
                </div>
                <label for="rss_url"><?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?></label>
            
            <?php endif; ?>
        </div>
    </div>
    <div class="buttons-set form-buttons">
        <span class="required-field pull-right"><?php echo $this->__('* Required Fields') ?></span>
        <button type="submit" title="<?php echo $this->__('Share Wishlist') ?>" class="button btn btn-primary"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
Validation.addAllThese([
    ['validate-emails', '<?php echo $this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.') ?>', function (v) {
    if(Validation.get('IsEmpty').test(v)) {
        return true;
    }

    var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
    var emails = v.split(',');

    for (var i=0; i<emails.length; i++) {
        if(!valid_regexp.test(emails[i].strip())) {
            return false;
        }
    }

    return true;
    }]
]);
var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
