<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="row">
    <div class="span9">
        <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <div class="my-wishlist">
                <h1 class="page-title title-buttons"><?php echo $this->getTitle(); ?>
                    <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
                    <a href="<?php echo $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>" class="link-rss btn btn-primary pull-right"><?php echo $this->__('RSS Feed') ?></a>
                <?php endif; ?>
                </h1>
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

                <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" method="post">
                    <?php echo $this->getChildHtml('top'); ?>
                    <fieldset>
                        <?php if ($this->hasWishlistItems()): ?>
                            <div class="table-box">
                                <?php echo $this->getBlockHtml('formkey');?>
                                <?php $this->getChild('items')->setItems($this->getWishlistItems()); ?>
                                <?php echo $this->getChildHtml('items');?>
                                <script type="text/javascript">decorateTable('wishlist-table')</script>
                            </div>
                        <?php else: ?>
                            <p class="wishlist-empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
                        <?php endif ?>
                        <div class="buttons-set buttons-set2">
                            <?php echo $this->getChild('control_buttons')->toHtml();?>
                        </div>
                    </fieldset>
                </form>

                <script type="text/javascript">
                //<![CDATA[
                var wishlistForm = new Validation($('wishlist-view-form'));
                function addAllWItemsToCart() {
                    var url = '<?php echo $this->getUrl('*/*/allcart', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>';
                    var separator = (url.indexOf('?') >= 0) ? '&' : '?';
                    $$('#wishlist-view-form .qty').each(
                        function (input, index) {
                            url += separator + input.name + '=' + encodeURIComponent(input.value);
                            separator = '&';
                        }
                    );
                    setLocation(url);
                }
                //]]>
                </script>
            </div>
            <?php echo $this->getChildHtml('bottom'); ?>
            <div class="buttons-set">
                <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            </div>
        <?php endif ?>
    </div>
</div>