<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <span class="arrow">&nbsp;</span>
        <?php if ($_item->getCount() > 0): ?>
        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
            <?php echo $_item->getLabel() ?>
            <?php if ($this->shouldDisplayProductCount()): ?>
                (<?php echo $_item->getCount() ?>)
            <?php endif; ?>
        </a>
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
    </li>
<?php endforeach ?>
