<?php
/**
 * Precise Magento Theme
 *
 * @category    design
 * @package     precise_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<h1 class="page-title"><?php echo Mage::helper('sales')->__('Returns') ?></h1>
<div class="block-content returns">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
       <div class="form-alt">
           
               
                   <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <span class="required">*</span></label>
               
               
                   <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" style="width:300px;"/>
               
           
           
                  <div>
                   <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
                  </div>
           
           
           
                   <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <span class="required">*</span></label>
           
           
                   <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;"/>
           
           
           
           
                   <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
               
               
                   <select name="oar_type" id="quick_search_type_id" class="guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               
           
           <div id="oar-email" style="clear:both;">
               
                   <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <span class="required">*</span></label>
               
               
                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  style="width:300px;"/>
               
           </div>
           <div id="oar-zip" style="display:none;clear:both;">
               
                   <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <span class="required">*</span></label>
               
               
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" style="width:300px;"/>
               
           </div>
           <div style="clear:both;">
               <div class="input-box" style="float:left;text-align:right;width:455px">
                   <button type="submit" title="Continue" class="button btn btn-primary pull-left"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
               </div>
           </div>
       </div>
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
